### ISSUE TITLE
Flatpak version uses a light theme on elementary OS.

### ISSUE THREAD

**Issue by marco4mp** [flathub/org.gnome.gThumb#3]
**The problem**
I installed the Flathub version of gThumb on elementary OS. But instead of using the dark theme it uses a light one.

![Captura realizada el 2021-11-17 12 54 25](https://user-images.githubusercontent.com/52709674/142234643-57a808ec-1da4-4dc1-9a31-6145293b8176.png)

**Additional Info**
"Apt install" version from Ubuntu repository works fine (it has dark theme). 
On Fedora 34 (Gnome), Flathub version works fine too.

Sorry, I'm not a developer so I don't know how to investigate the problem.

**Comment by fedelibre** [comment]
It seems a problem with Elementary OS, so I'll close this issue.

You should find an answer [here](https://elementaryos.stackexchange.com/questions/28475/how-to-get-elementaryos-odin-6-0-flatpak-apps-to-use-the-system-dark-theme).
