### ISSUE TITLE
GThumb from flathub doesn't bundle support for JPEG XL?

### ISSUE THREAD

**Issue by nekohayo** [flathub/org.gnome.gThumb#4]
GThumb 3.12 supports JXL, but the version packaged in flathub doesn't seem to have it? Or am I imagining things?

**Comment by fedelibre** [comment]
Never heard before :-)

Can you please upload a JXL file here?

**Comment by nekohayo** [comment]
It's The Future™ :)
Check out https://jpegxl.info for your curiosity / to learn more.

I cannot attach a sample file because it is not among GitHub's authorized formats.

https://jpegxl.info/art/ has some sample images in that format (in Firefox you'll need to right-click the little broken image icon below the "Tropical Island Sunset with JXL logo overlay" and "Open image in new tab" to download it) that you could download and try to open in gthumb. I was able to view it with gthumb in opensuse, but not the flatpak version.

**Comment by fedelibre** [comment]
@nekohayo You can test the latest flatpak of PR #5 

It's working here:

![Screenshot from 2021-11-23 23-04-50](https://user-images.githubusercontent.com/1644647/143136853-cd661339-af26-4ca8-98c0-83c9c9d7a309.png)
